### ISSUE TITLE
Filedescriptor leak on OS X

### ISSUE THREAD

**Issue by kryoxide** [jgoerzen/ftphs#15]
Repeatedly using ```getbinary``` on a nonexistent file leads to a file leads to a filedescriptor leak.

This seems to be due to ```forceioresp 100 r``` in ```ntransfercmd``` throwing an ```IOError```, that is thrown from the function without closing a previously opened socket first.

**Comment by kryoxide** [comment]
Below is a minimal example that is needed to reproduce the code
```haskell
    import Control.Monad (replicateM)
    import Control.Monad.Catch (catchIOError)
    import Network.FTP.Client

    length <$> replicateM 10000 (catchIOError (getbinary ftpConnection "x" >> return ()) 
                                              (\_ -> putStr ".")
                                )
```

**Comment by jessekempf** [comment]
@kryoxide: FWIW, I ran into the same problem.

I submitted #17 to fix this issue.
